import { MODULES } from "@/lib/modules";
import { buildSectionsFromMenus } from "./build-nav";
import { a, g, simpleGuide } from "./helpers";
import type { GuideModuleId, ModuleGuideNav } from "./types";

const F = "finance" as GuideModuleId;
const O = "operasional" as GuideModuleId;
const H = "hris" as GuideModuleId;

const financeMenus = MODULES.find((m) => m.id === "finance")!.menus;

export const financeGuideNav: ModuleGuideNav = {
  moduleId: "finance",
  title: "Panduan Finance",
  subtitle: "Klik menu di kiri — alur kerja ditampilkan dari atas ke bawah.",
  sections: buildSectionsFromMenus(financeMenus),
  guides: {
    dashboard: g(
      "dashboard",
      "Ringkasan Modul Finance",
      "Dashboard",
      "/finance",
      "Pembukuan Accurate-style — buku besar, kas/bank, penjualan, pembelian, persediaan, laporan.",
      [
        a(O, "Sumber transaksi: OPB, PO, Stock Opname", "/operasional"),
        a(F, "Post faktur → jurnal otomatis"),
        a(F, "Kas/Bank: penerimaan & pembayaran"),
        a(F, "Laporan keuangan: Laba Rugi, Neraca, Arus Kas"),
        a(H, "Payroll → Gaji & Tunjangan", "/finance/perusahaan/gaji-tunjangan"),
      ],
    ),

    // ── Buku Besar ──
    "buku-besar-akun-perkiraan": simpleGuide(
      "buku-besar-akun-perkiraan",
      "Akun Perkiraan",
      "/finance/buku-besar/akun-perkiraan",
      "Chart of accounts (COA) — struktur akun debit/kredit.",
      F,
      ["Buka Akun Perkiraan", "Review hierarki akun", "Tambah / edit akun", "Set tipe & saldo normal"],
    ),
    "buku-besar-pencatatan-beban": simpleGuide(
      "buku-besar-pencatatan-beban",
      "Pencatatan Beban",
      "/finance/buku-besar/pencatatan-beban",
      "Catat beban operasional langsung ke akun beban.",
      F,
      ["Buka Pencatatan Beban", "Pilih akun beban & sumber dana", "Isi nominal & keterangan", "Simpan → jurnal otomatis"],
    ),
    "buku-besar-jurnal-umum": g(
      "buku-besar-jurnal-umum",
      "Jurnal Umum",
      "Jurnal Umum",
      "/finance/buku-besar/jurnal-umum",
      "Entry jurnal manual — penyesuaian, akrual, koreksi.",
      [
        a(F, "Buka Jurnal Umum", "/finance/buku-besar/jurnal-umum"),
        a(F, "Buat jurnal baru"),
        a(F, "Isi baris debit & kredit (balance)"),
        a(F, "Post jurnal"),
        a(F, "Review di Histori Akun", "/finance/buku-besar/histori-akun"),
        a(F, "Log perubahan di Log Aktivitas Jurnal", "/finance/buku-besar/log-aktivitas-jurnal"),
      ],
    ),
    "buku-besar-anggaran": simpleGuide(
      "buku-besar-anggaran",
      "Anggaran",
      "/finance/buku-besar/anggaran",
      "Budget vs realisasi per akun/periode.",
      F,
      ["Buka Anggaran", "Set target per akun", "Monitor realisasi vs budget"],
    ),
    "buku-besar-histori-akun": simpleGuide(
      "buku-besar-histori-akun",
      "Histori Akun",
      "/finance/buku-besar/histori-akun",
      "Ledger per akun — semua mutasi debit/kredit.",
      F,
      ["Pilih akun perkiraan", "Filter periode", "Review saldo berjalan", "Drill-down ke jurnal sumber"],
    ),
    "buku-besar-log-aktivitas-jurnal": simpleGuide(
      "buku-besar-log-aktivitas-jurnal",
      "Log Aktivitas Jurnal",
      "/finance/buku-besar/log-aktivitas-jurnal",
      "Audit trail perubahan jurnal — siapa, kapan, apa.",
      F,
      ["Buka Log Aktivitas Jurnal", "Filter user & tanggal", "Review create/edit/delete jurnal"],
    ),

    // ── Kas & Bank ──
    "kas-bank-pembayaran": g(
      "kas-bank-pembayaran",
      "Pembayaran",
      "Pembayaran",
      "/finance/kas-bank/pembayaran",
      "Catat pengeluaran kas/bank — hutang supplier, beban, dll.",
      [
        a(F, "Buka Pembayaran", "/finance/kas-bank/pembayaran"),
        a(F, "Pilih sumber kas/bank"),
        a(F, "Link ke faktur pembelian / beban"),
        a(F, "Post → jurnal & update saldo hutang"),
        a(F, "Review di Rekening Koran", "/finance/kas-bank/rekening-koran"),
      ],
    ),
    "kas-bank-penerimaan": g(
      "kas-bank-penerimaan",
      "Penerimaan",
      "Penerimaan",
      "/finance/kas-bank/penerimaan",
      "Catat penerimaan kas/bank — piutang pelanggan, pendapatan lain.",
      [
        a(F, "Buka Penerimaan", "/finance/kas-bank/penerimaan"),
        a(F, "Pilih rekening tujuan"),
        a(F, "Link ke faktur penjualan / piutang"),
        a(F, "Post → jurnal & update saldo piutang"),
      ],
    ),
    "kas-bank-transfer-bank": g(
      "kas-bank-transfer-bank",
      "Transfer Bank",
      "Transfer Bank",
      "/finance/kas-bank/transfer-bank",
      "Transfer antar rekening bank/kas internal.",
      [
        a(F, "Buka Transfer Bank", "/finance/kas-bank/transfer-bank"),
        a(F, "Pilih rekening asal & tujuan"),
        a(F, "Isi nominal & keterangan"),
        a(F, "Post → jurnal transfer otomatis"),
        a(F, "Verifikasi di Histori Bank", "/finance/kas-bank/histori-bank"),
      ],
    ),
    "kas-bank-rekening-koran": simpleGuide(
      "kas-bank-rekening-koran",
      "Rekening Koran",
      "/finance/kas-bank/rekening-koran",
      "Statement mutasi per rekening bank.",
      F,
      ["Pilih rekening bank", "Filter periode", "Review mutasi masuk/keluar", "Export statement"],
    ),
    "kas-bank-rekonsiliasi-bank": g(
      "kas-bank-rekonsiliasi-bank",
      "Rekonsiliasi Bank",
      "Rekonsiliasi Bank",
      "/finance/kas-bank/rekonsiliasi-bank",
      "Cocokkan saldo buku vs mutasi bank.",
      [
        a(F, "Buka Rekonsiliasi Bank", "/finance/kas-bank/rekonsiliasi-bank"),
        a(F, "Pilih rekening & periode"),
        a(F, "Tick transaksi yang sudah cocok"),
        a(F, "Identifikasi selisih / outstanding"),
        a(F, "Finalisasi rekonsiliasi"),
      ],
    ),
    "kas-bank-histori-bank": simpleGuide(
      "kas-bank-histori-bank",
      "Histori Bank",
      "/finance/kas-bank/histori-bank",
      "Riwayat semua transaksi kas & bank.",
      F,
      ["Filter rekening & periode", "Review transaksi", "Drill-down ke dokumen sumber"],
    ),

    // ── Penjualan ──
    "penjualan-faktur-penjualan": g(
      "penjualan-faktur-penjualan",
      "Faktur Penjualan (OPB → Faktur → Jurnal)",
      "Faktur Penjualan",
      "/finance/penjualan/faktur-penjualan",
      "Buat faktur dari OPB yang sudah ditagihkan — post ke jurnal piutang & pendapatan.",
      [
        a(O, "OPB status Ditagihkan di Operasional", "/operasional/opb"),
        a(F, "Buat Faktur Penjualan dari OPB", "/finance/penjualan/faktur-penjualan"),
        a(F, "Review item, PPN, total tagihan"),
        a(F, "Post faktur → jurnal otomatis"),
        a(F, "Status: Open / Partial / Lunas"),
        a(F, "Catat Penerimaan Penjualan", "/finance/penjualan/penerimaan-penjualan"),
      ],
    ),
    "penjualan-penerimaan-penjualan": g(
      "penjualan-penerimaan-penjualan",
      "Penerimaan Penjualan",
      "Penerimaan Penjualan",
      "/finance/penjualan/penerimaan-penjualan",
      "Catat pelunasan faktur penjualan — update piutang & saldo kas.",
      [
        a(F, "Buka Penerimaan Penjualan", "/finance/penjualan/penerimaan-penjualan"),
        a(F, "Pilih faktur open/partial"),
        a(F, "Isi nominal penerimaan"),
        a(F, "Post → jurnal piutang & kas"),
        a(F, "Faktur lunas jika total terbayar"),
        a(F, "Monitor piutang di Laporan Hutang Piutang", "/finance/laporan/hutang-piutang"),
      ],
    ),
    "penjualan-uang-muka-penjualan": simpleGuide(
      "penjualan-uang-muka-penjualan",
      "Uang Muka Penjualan",
      "/finance/penjualan/uang-muka-penjualan",
      "Catat DP/uang muka dari pelanggan sebelum faktur penuh.",
      F,
      ["Catat uang muka pelanggan", "Link ke pelanggan/OPB", "Saldo Uang Muka → offset saat faktur"],
    ),
    "penjualan-retur-penjualan": simpleGuide(
      "penjualan-retur-penjualan",
      "Retur Penjualan",
      "/finance/penjualan/retur-penjualan",
      "Proses retur/koreksi tagihan penjualan.",
      F,
      ["Buat retur dari faktur", "Review item & nominal retur", "Post → jurnal koreksi piutang/pendapatan"],
    ),
    "penjualan-pelanggan": g(
      "penjualan-pelanggan",
      "Master Pelanggan",
      "Pelanggan",
      "/finance/penjualan/pelanggan",
      "Data pelanggan/cabang bengkel untuk faktur penjualan.",
      [
        a(F, "Buka daftar Pelanggan", "/finance/penjualan/pelanggan"),
        a(F, "Tambah / edit data pelanggan"),
        a(F, "Set syarat pembayaran", "/finance/perusahaan/syarat-pembayaran"),
        a(O, "Cabang terkait di Master Cabang", "/operasional/cabang"),
      ],
    ),

    // ── Persediaan ──
    "persediaan-penyesuaian-persediaan": g(
      "persediaan-penyesuaian-persediaan",
      "Penyesuaian Persediaan (Stock Opname → Jurnal)",
      "Penyesuaian Persediaan",
      "/finance/persediaan/penyesuaian-persediaan",
      "Koreksi stok setelah stock opname — posting ke jurnal persediaan.",
      [
        a(O, "Stock Opname approved di Operasional", "/operasional/stock-opname"),
        a(F, "Buat Penyesuaian Persediaan", "/finance/persediaan/penyesuaian-persediaan"),
        a(F, "Review selisih qty & nilai"),
        a(F, "Post penyesuaian → jurnal otomatis"),
        a(F, "Saldo persediaan terupdate"),
      ],
    ),
    "persediaan-penerimaan-barang": g(
      "persediaan-penerimaan-barang",
      "Penerimaan Barang (Persediaan)",
      "Penerimaan Barang",
      "/finance/persediaan/penerimaan-barang",
      "Mirror penerimaan barang — stok masuk ke gudang.",
      [
        a(O, "Goods Received di PO Operasional", "/operasional/po"),
        a(F, "Review Penerimaan Barang", "/finance/persediaan/penerimaan-barang"),
        a(F, "Post → jurnal persediaan"),
      ],
    ),
    "persediaan-barang-jasa": simpleGuide(
      "persediaan-barang-jasa",
      "Barang & Jasa",
      "/finance/persediaan/barang-jasa",
      "Master item persediaan — sync dengan Master Produk Operasional.",
      F,
      ["Kelola daftar barang & jasa", "Set akun persediaan & HPP", "Link ke Master Produk Operasional"],
    ),
    "persediaan-barang-per-gudang": simpleGuide(
      "persediaan-barang-per-gudang",
      "Barang Per Gudang",
      "/finance/persediaan/barang-per-gudang",
      "Saldo stok per gudang/lokasi.",
      F,
      ["Pilih gudang", "Review saldo per item", "Drill-down mutasi stok"],
    ),
    "persediaan-barang-stok-minimum": simpleGuide(
      "persediaan-barang-stok-minimum",
      "Barang Stok Minimum",
      "/finance/persediaan/barang-stok-minimum",
      "Alert stok di bawah minimum — trigger ajuan stok.",
      F,
      ["Review item di bawah minimum", "Alert ke Operasional → Ajuan Stok"],
    ),

    // ── Pembelian ──
    "pembelian-pesanan-pembelian": g(
      "pembelian-pesanan-pembelian",
      "Pesanan Pembelian",
      "Pesanan Pembelian",
      "/finance/pembelian/pesanan-pembelian",
      "Mirror PO Operasional — monitor status pembelian.",
      [
        a(O, "Buat PO di Operasional", "/operasional/po"),
        a(F, "Review Pesanan Pembelian", "/finance/pembelian/pesanan-pembelian"),
        a(F, "Track status: open / partial / closed"),
      ],
    ),
    "pembelian-faktur-pembelian": g(
      "pembelian-faktur-pembelian",
      "Faktur Pembelian (PO → Faktur → Jurnal)",
      "Faktur Pembelian",
      "/finance/pembelian/faktur-pembelian",
      "Catat faktur supplier setelah penerimaan barang — post ke jurnal hutang.",
      [
        a(O, "PO & Goods Received di Operasional", "/operasional/po"),
        a(F, "Buat Faktur Pembelian dari PO/GR", "/finance/pembelian/faktur-pembelian"),
        a(F, "Review PPN & total hutang"),
        a(F, "Post faktur → jurnal otomatis"),
        a(F, "Bayar via Pembayaran Pembelian", "/finance/pembelian/pembayaran-pembelian"),
      ],
    ),
    "pembelian-uang-muka-pembelian": simpleGuide(
      "pembelian-uang-muka-pembelian",
      "Uang Muka Pembelian",
      "/finance/pembelian/uang-muka-pembelian",
      "Catat DP ke supplier sebelum faktur penuh.",
      F,
      ["Catat uang muka pembelian", "Link ke PO", "Saldo DP → offset saat faktur"],
    ),
    "pembelian-pembayaran-pembelian": g(
      "pembelian-pembayaran-pembelian",
      "Pembayaran Pembelian",
      "Pembayaran Pembelian",
      "/finance/pembelian/pembayaran-pembelian",
      "Urutan: DP → GR → faktur → pelunasan.",
      [
        a(F, "Catat DP (jika ada)", "/finance/pembelian/uang-muka-pembelian"),
        a(F, "Catat faktur pembelian", "/finance/pembelian/faktur-pembelian"),
        a(F, "Catat pelunasan / angsuran", "/finance/pembelian/pembayaran-pembelian"),
        a(F, "Post → jurnal hutang & kas"),
        a(F, "Monitor hutang di Laporan Hutang Piutang", "/finance/laporan/hutang-piutang"),
      ],
    ),
    "pembelian-penerimaan-barang": g(
      "pembelian-penerimaan-barang",
      "Penerimaan Barang (Pembelian)",
      "Penerimaan Barang",
      "/finance/pembelian/penerimaan-barang",
      "Mirror GR Operasional — verifikasi sebelum faktur.",
      [
        a(O, "Goods Received di Operasional", "/operasional/po"),
        a(F, "Review Penerimaan Barang Pembelian", "/finance/pembelian/penerimaan-barang"),
        a(F, "Lanjut Faktur Pembelian", "/finance/pembelian/faktur-pembelian"),
      ],
    ),
    "pembelian-pemasok": g(
      "pembelian-pemasok",
      "Master Pemasok",
      "Pemasok",
      "/finance/pembelian/pemasok",
      "Data supplier/pabrik cat untuk pembelian.",
      [
        a(F, "Buka daftar Pemasok", "/finance/pembelian/pemasok"),
        a(F, "Tambah / edit data supplier"),
        a(F, "Set syarat pembayaran & NPWP"),
        a(O, "PO ke pemasok di Operasional", "/operasional/po"),
      ],
    ),

    // ── Aset Tetap ──
    "aset-tetap-aset-tetap": simpleGuide(
      "aset-tetap-aset-tetap",
      "Aset Tetap",
      "/finance/aset-tetap/aset-tetap",
      "Register aset tetap perusahaan — kendaraan, peralatan, dll.",
      F,
      ["Daftar aset tetap", "Input harga perolehan & masa manfaat", "Hitung penyusutan otomatis"],
    ),
    "aset-tetap-kategori-aset": simpleGuide(
      "aset-tetap-kategori-aset",
      "Kategori Aset",
      "/finance/aset-tetap/kategori-aset",
      "Kategori & metode penyusutan aset.",
      F,
      ["Kelola kategori aset", "Set metode & tarif penyusutan"],
    ),
    "aset-tetap-perubahan-aset-tetap": simpleGuide(
      "aset-tetap-perubahan-aset-tetap",
      "Perubahan Aset Tetap",
      "/finance/aset-tetap/perubahan-aset-tetap",
      "Revaluasi, penambahan nilai, atau koreksi aset.",
      F,
      ["Pilih aset", "Catat perubahan nilai", "Post jurnal penyesuaian"],
    ),
    "aset-tetap-disposisi-aset-tetap": simpleGuide(
      "aset-tetap-disposisi-aset-tetap",
      "Disposisi Aset Tetap",
      "/finance/aset-tetap/disposisi-aset-tetap",
      "Jual/hapus aset tetap — hitung gain/loss.",
      F,
      ["Pilih aset untuk disposisi", "Input harga jual / alasan hapus", "Post jurnal disposisi"],
    ),
    "aset-tetap-pindah-aset": simpleGuide(
      "aset-tetap-pindah-aset",
      "Pindah Aset",
      "/finance/aset-tetap/pindah-aset",
      "Transfer aset antar lokasi/cabang.",
      F,
      ["Pilih aset & lokasi tujuan", "Simpan perpindahan", "Update lokasi aset"],
    ),
    "aset-tetap-aset-per-lokasi": simpleGuide(
      "aset-tetap-aset-per-lokasi",
      "Aset per Lokasi",
      "/finance/aset-tetap/aset-per-lokasi",
      "Daftar aset per cabang/lokasi.",
      F,
      ["Filter per lokasi", "Review nilai buku aset", "Export laporan"],
    ),

    // ── Perusahaan ──
    "perusahaan-syarat-pembayaran": simpleGuide(
      "perusahaan-syarat-pembayaran",
      "Syarat Pembayaran",
      "/finance/perusahaan/syarat-pembayaran",
      "Termin pembayaran — net 7, net 30, dll.",
      F,
      ["Kelola syarat pembayaran", "Assign ke pelanggan/pemasok"],
    ),
    "perusahaan-proses-akhir-bulan": simpleGuide(
      "perusahaan-proses-akhir-bulan",
      "Proses Akhir Bulan",
      "/finance/perusahaan/proses-akhir-bulan",
      "Closing period — akrual, penyusutan, lock periode.",
      F,
      ["Jalankan proses akhir bulan", "Review akrual & penyusutan", "Lock periode akuntansi"],
    ),
    "perusahaan-gaji-tunjangan": g(
      "perusahaan-gaji-tunjangan",
      "Gaji & Tunjangan (HRIS → Finance)",
      "Gaji & Tunjangan",
      "/finance/perusahaan/gaji-tunjangan",
      "Posting payroll dari HRIS ke jurnal beban gaji.",
      [
        a(H, "Slip gaji final di HRIS", "/hris/slip-gaji"),
        a(F, "Review Gaji & Tunjangan", "/finance/perusahaan/gaji-tunjangan"),
        a(F, "Post payroll → jurnal beban gaji & hutang"),
        a(F, "Bayar gaji via Pembayaran", "/finance/kas-bank/pembayaran"),
      ],
    ),
    "perusahaan-karyawan": simpleGuide(
      "perusahaan-karyawan",
      "Karyawan (Finance)",
      "/finance/perusahaan/karyawan",
      "Mirror data karyawan untuk keperluan akuntansi payroll.",
      F,
      ["Review data karyawan", "Sync dengan HRIS Karyawan"],
    ),
    "perusahaan-transaksi-berulang": simpleGuide(
      "perusahaan-transaksi-berulang",
      "Transaksi Berulang",
      "/finance/perusahaan/transaksi-berulang",
      "Template jurnal/transaksi rutin bulanan.",
      F,
      ["Setup transaksi berulang", "Set jadwal & nominal", "Generate otomatis per periode"],
    ),
    "perusahaan-kalender": simpleGuide(
      "perusahaan-kalender",
      "Kalender",
      "/finance/perusahaan/kalender",
      "Kalender fiskal & jadwal closing.",
      F,
      ["Review kalender fiskal", "Set tanggal closing & libur"],
    ),
    "perusahaan-kontak": simpleGuide(
      "perusahaan-kontak",
      "Kontak",
      "/finance/perusahaan/kontak",
      "Buku alamat kontak bisnis.",
      F,
      ["Kelola kontak", "Link ke pelanggan/pemasok"],
    ),
    "perusahaan-transaksi-favorit": simpleGuide(
      "perusahaan-transaksi-favorit",
      "Transaksi Favorit",
      "/finance/perusahaan/transaksi-favorit",
      "Shortcut transaksi yang sering dipakai.",
      F,
      ["Simpan template favorit", "Quick entry dari favorit"],
    ),
    "perusahaan-log-aktivitas": simpleGuide(
      "perusahaan-log-aktivitas",
      "Log Aktivitas",
      "/finance/perusahaan/log-aktivitas",
      "Audit log aktivitas modul Finance.",
      F,
      ["Review log user & aksi", "Filter periode & modul"],
    ),

    // ── Laporan Keuangan ──
    "laporan-laba-rugi": simpleGuide(
      "laporan-laba-rugi",
      "Laba Rugi",
      "/finance/laporan/laba-rugi",
      "Profit & loss statement per periode.",
      F,
      ["Pilih periode", "Generate Laba Rugi", "Review pendapatan vs beban", "Export PDF/Excel"],
    ),
    "laporan-neraca": simpleGuide(
      "laporan-neraca",
      "Neraca",
      "/finance/laporan/neraca",
      "Balance sheet — aset, liabilitas, ekuitas.",
      F,
      ["Pilih tanggal neraca", "Generate laporan", "Review pos keuangan"],
    ),
    "laporan-arus-kas": simpleGuide(
      "laporan-arus-kas",
      "Arus Kas",
      "/finance/laporan/arus-kas",
      "Cash flow statement — operasi, investasi, pendanaan.",
      F,
      ["Pilih periode", "Generate Arus Kas", "Review sumber & penggunaan kas"],
    ),
    "laporan-laba-ditahan": simpleGuide(
      "laporan-laba-ditahan",
      "Laba Ditahan",
      "/finance/laporan/laba-ditahan",
      "Perubahan saldo laba ditahan.",
      F,
      ["Generate laporan laba ditahan", "Review mutasi per periode"],
    ),
    "laporan-rasio-keuangan": simpleGuide(
      "laporan-rasio-keuangan",
      "Rasio Keuangan",
      "/finance/laporan/rasio-keuangan",
      "Financial ratios — likuiditas, profitabilitas, leverage.",
      F,
      ["Generate rasio keuangan", "Review KPI finansial", "Bandingkan antar periode"],
    ),
    "laporan-perubahan-equitas": simpleGuide(
      "laporan-perubahan-equitas",
      "Perubahan Equitas",
      "/finance/laporan/perubahan-equitas",
      "Statement of changes in equity.",
      F,
      ["Generate laporan equitas", "Review komponen perubahan"],
    ),
    "laporan-grafik": simpleGuide(
      "laporan-grafik",
      "Grafik",
      "/finance/laporan/grafik",
      "Visualisasi trend keuangan.",
      F,
      ["Pilih metrik & periode", "Review grafik trend", "Export chart"],
    ),
    "laporan-laporan-penjualan": g(
      "laporan-laporan-penjualan",
      "Laporan Penjualan",
      "Laporan Penjualan",
      "/finance/laporan/laporan-penjualan",
      "Rekap penjualan per cabang/pelanggan/periode.",
      [
        a(F, "Generate Laporan Penjualan", "/finance/laporan/laporan-penjualan"),
        a(F, "Filter cabang & periode"),
        a(O, "Cross-check dengan OPB Operasional", "/operasional/opb"),
      ],
    ),
    "laporan-laporan-pembelian": g(
      "laporan-laporan-pembelian",
      "Laporan Pembelian",
      "Laporan Pembelian",
      "/finance/laporan/laporan-pembelian",
      "Rekap pembelian per supplier/periode.",
      [
        a(F, "Generate Laporan Pembelian", "/finance/laporan/laporan-pembelian"),
        a(O, "Cross-check dengan PO Operasional", "/operasional/po"),
      ],
    ),
    "laporan-hutang-piutang": g(
      "laporan-hutang-piutang",
      "Laporan Hutang Piutang",
      "Hutang Piutang",
      "/finance/laporan/hutang-piutang",
      "Aging piutang pelanggan & hutang supplier.",
      [
        a(F, "Generate Laporan Hutang Piutang", "/finance/laporan/hutang-piutang"),
        a(F, "Review aging piutang (faktur jual)"),
        a(F, "Review aging hutang (faktur beli)"),
        a(F, "Follow-up pelunasan", "/finance/kas-bank/penerimaan"),
      ],
    ),
    "laporan-perpajakan": simpleGuide(
      "laporan-perpajakan",
      "Perpajakan",
      "/finance/laporan/perpajakan",
      "Rekap PPN masukan/keluaran & kewajiban pajak.",
      F,
      ["Generate laporan pajak", "Review PPN & PPh", "Export untuk e-Filing"],
    ),
    "daftar-laporan": g(
      "daftar-laporan",
      "Daftar Laporan",
      "Daftar Laporan",
      "/finance/daftar-laporan",
      "Katalog semua laporan Finance — shortcut ke laporan spesifik.",
      [
        a(F, "Buka Daftar Laporan", "/finance/daftar-laporan"),
        a(F, "Pilih kategori laporan"),
        a(F, "Set parameter & generate"),
        a(F, "Export / print hasil"),
      ],
    ),
  },
};
